services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      user: ${user:-}
      password: ${password:-}
      host: ${host:-}
      port: ${port:-6543}
      dbname: ${dbname:-postgres}
    restart: unless-stopped
